//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Интернет_магазин
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись в отчете.
    /// </summary>
    // *** Start programmer edit section *** (ЗаписьВОтчете CustomAttributes)

    // *** End programmer edit section *** (ЗаписьВОтчете CustomAttributes)
    [AutoAltered()]
    [Caption("Запись в отчете")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьВОтчетеE", new string[] {
            "Количество as \'Количество\'",
            "Сумма as \'Сумма\'",
            "Товар as \'Товар\'",
            "Товар.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Товар.Наименование"})]
    [MasterViewDefineAttribute("ЗаписьВОтчетеE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ЗаписьВОтчете : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private double fСумма;
        
        private IIS.Интернет_магазин.Товар fТовар;
        
        private IIS.Интернет_магазин.Отчет fОтчет;
        
        // *** Start programmer edit section *** (ЗаписьВОтчете CustomMembers)

        // *** End programmer edit section *** (ЗаписьВОтчете CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВОтчете.Количество CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВОтчете.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВОтчете.Количество Get start)

                // *** End programmer edit section *** (ЗаписьВОтчете.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ЗаписьВОтчете.Количество Get end)

                // *** End programmer edit section *** (ЗаписьВОтчете.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВОтчете.Количество Set start)

                // *** End programmer edit section *** (ЗаписьВОтчете.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ЗаписьВОтчете.Количество Set end)

                // *** End programmer edit section *** (ЗаписьВОтчете.Количество Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВОтчете.Сумма CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВОтчете.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВОтчете.Сумма Get start)

                // *** End programmer edit section *** (ЗаписьВОтчете.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (ЗаписьВОтчете.Сумма Get end)

                // *** End programmer edit section *** (ЗаписьВОтчете.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВОтчете.Сумма Set start)

                // *** End programmer edit section *** (ЗаписьВОтчете.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ЗаписьВОтчете.Сумма Set end)

                // *** End programmer edit section *** (ЗаписьВОтчете.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Запись в отчете.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВОтчете.Товар CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВОтчете.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.Интернет_магазин.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВОтчете.Товар Get start)

                // *** End programmer edit section *** (ЗаписьВОтчете.Товар Get start)
                IIS.Интернет_магазин.Товар result = this.fТовар;
                // *** Start programmer edit section *** (ЗаписьВОтчете.Товар Get end)

                // *** End programmer edit section *** (ЗаписьВОтчете.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВОтчете.Товар Set start)

                // *** End programmer edit section *** (ЗаписьВОтчете.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (ЗаписьВОтчете.Товар Set end)

                // *** End programmer edit section *** (ЗаписьВОтчете.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Интернет_магазин.Отчет.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьВОтчете.Отчет CustomAttributes)

        // *** End programmer edit section *** (ЗаписьВОтчете.Отчет CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Отчет"})]
        public virtual IIS.Интернет_магазин.Отчет Отчет
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьВОтчете.Отчет Get start)

                // *** End programmer edit section *** (ЗаписьВОтчете.Отчет Get start)
                IIS.Интернет_магазин.Отчет result = this.fОтчет;
                // *** Start programmer edit section *** (ЗаписьВОтчете.Отчет Get end)

                // *** End programmer edit section *** (ЗаписьВОтчете.Отчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьВОтчете.Отчет Set start)

                // *** End programmer edit section *** (ЗаписьВОтчете.Отчет Set start)
                this.fОтчет = value;
                // *** Start programmer edit section *** (ЗаписьВОтчете.Отчет Set end)

                // *** End programmer edit section *** (ЗаписьВОтчете.Отчет Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьВОтчетеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьВОтчетеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьВОтчетеE", typeof(IIS.Интернет_магазин.ЗаписьВОтчете));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ЗаписьВОтчете.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfЗаписьВОтчете CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfЗаписьВОтчете CustomAttributes)
    public class DetailArrayOfЗаписьВОтчете : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Интернет_магазин.DetailArrayOfЗаписьВОтчете members)

        // *** End programmer edit section *** (IIS.Интернет_магазин.DetailArrayOfЗаписьВОтчете members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ЗаписьВОтчете by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ЗаписьВОтчете.
        /// </summary>
        public DetailArrayOfЗаписьВОтчете(IIS.Интернет_магазин.Отчет fОтчет) : 
                base(typeof(ЗаписьВОтчете), ((ICSSoft.STORMNET.DataObject)(fОтчет)))
        {
        }
        
        public IIS.Интернет_магазин.ЗаписьВОтчете this[int index]
        {
            get
            {
                return ((IIS.Интернет_магазин.ЗаписьВОтчете)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Интернет_магазин.ЗаписьВОтчете dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
