//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Интернет_магазин
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отчет.
    /// </summary>
    // *** Start programmer edit section *** (Отчет CustomAttributes)

    // *** End programmer edit section *** (Отчет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтчетE", new string[] {
            "Год as \'Год\'",
            "Месяц as \'Месяц\'"})]
    [AssociatedDetailViewAttribute("ОтчетE", "ЗаписьВОтчете", "ЗаписьВОтчетеE", true, "", "Запись в отчете", true, new string[] {
            ""})]
    [View("ОтчетL", new string[] {
            "Год as \'Год\'",
            "Месяц as \'Месяц\'"})]
    public class Отчет : ICSSoft.STORMNET.DataObject
    {
        
        private int fГод;
        
        private int fМесяц;
        
        private IIS.Интернет_магазин.DetailArrayOfЗаписьВОтчете fЗаписьВОтчете;
        
        // *** Start programmer edit section *** (Отчет CustomMembers)

        // *** End programmer edit section *** (Отчет CustomMembers)

        
        /// <summary>
        /// Год.
        /// </summary>
        // *** Start programmer edit section *** (Отчет.Год CustomAttributes)

        // *** End programmer edit section *** (Отчет.Год CustomAttributes)
        [NotNull()]
        public virtual int Год
        {
            get
            {
                // *** Start programmer edit section *** (Отчет.Год Get start)

                // *** End programmer edit section *** (Отчет.Год Get start)
                int result = this.fГод;
                // *** Start programmer edit section *** (Отчет.Год Get end)

                // *** End programmer edit section *** (Отчет.Год Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отчет.Год Set start)

                // *** End programmer edit section *** (Отчет.Год Set start)
                this.fГод = value;
                // *** Start programmer edit section *** (Отчет.Год Set end)

                // *** End programmer edit section *** (Отчет.Год Set end)
            }
        }
        
        /// <summary>
        /// Месяц.
        /// </summary>
        // *** Start programmer edit section *** (Отчет.Месяц CustomAttributes)

        // *** End programmer edit section *** (Отчет.Месяц CustomAttributes)
        [NotNull()]
        public virtual int Месяц
        {
            get
            {
                // *** Start programmer edit section *** (Отчет.Месяц Get start)

                // *** End programmer edit section *** (Отчет.Месяц Get start)
                int result = this.fМесяц;
                // *** Start programmer edit section *** (Отчет.Месяц Get end)

                // *** End programmer edit section *** (Отчет.Месяц Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отчет.Месяц Set start)

                // *** End programmer edit section *** (Отчет.Месяц Set start)
                this.fМесяц = value;
                // *** Start programmer edit section *** (Отчет.Месяц Set end)

                // *** End programmer edit section *** (Отчет.Месяц Set end)
            }
        }
        
        /// <summary>
        /// Отчет.
        /// </summary>
        // *** Start programmer edit section *** (Отчет.ЗаписьВОтчете CustomAttributes)

        // *** End programmer edit section *** (Отчет.ЗаписьВОтчете CustomAttributes)
        public virtual IIS.Интернет_магазин.DetailArrayOfЗаписьВОтчете ЗаписьВОтчете
        {
            get
            {
                // *** Start programmer edit section *** (Отчет.ЗаписьВОтчете Get start)

                // *** End programmer edit section *** (Отчет.ЗаписьВОтчете Get start)
                if ((this.fЗаписьВОтчете == null))
                {
                    this.fЗаписьВОтчете = new IIS.Интернет_магазин.DetailArrayOfЗаписьВОтчете(this);
                }
                IIS.Интернет_магазин.DetailArrayOfЗаписьВОтчете result = this.fЗаписьВОтчете;
                // *** Start programmer edit section *** (Отчет.ЗаписьВОтчете Get end)

                // *** End programmer edit section *** (Отчет.ЗаписьВОтчете Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Отчет.ЗаписьВОтчете Set start)

                // *** End programmer edit section *** (Отчет.ЗаписьВОтчете Set start)
                this.fЗаписьВОтчете = value;
                // *** Start programmer edit section *** (Отчет.ЗаписьВОтчете Set end)

                // *** End programmer edit section *** (Отчет.ЗаписьВОтчете Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтчетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетE", typeof(IIS.Интернет_магазин.Отчет));
                }
            }
            
            /// <summary>
            /// "ОтчетL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтчетL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтчетL", typeof(IIS.Интернет_магазин.Отчет));
                }
            }
        }
    }
}
