//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Интернет_магазин
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ТоварL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fНаименование;
        
        private double fCтоимость;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (Товар.ID CustomAttributes)

        // *** End programmer edit section *** (Товар.ID CustomAttributes)
        [DisableInsertProperty(true)]
        [NotNull()]
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (Товар.ID Get start)

                // *** End programmer edit section *** (Товар.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (Товар.ID Get end)

                // *** End programmer edit section *** (Товар.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.ID Set start)

                // *** End programmer edit section *** (Товар.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (Товар.ID Set end)

                // *** End programmer edit section *** (Товар.ID Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Наименование CustomAttributes)

        // *** End programmer edit section *** (Товар.Наименование CustomAttributes)
        [StrLen(255)]
        [NotNull()]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Наименование Get start)

                // *** End programmer edit section *** (Товар.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Товар.Наименование Get end)

                // *** End programmer edit section *** (Товар.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Наименование Set start)

                // *** End programmer edit section *** (Товар.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Товар.Наименование Set end)

                // *** End programmer edit section *** (Товар.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Cтоимость.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Cтоимость CustomAttributes)

        // *** End programmer edit section *** (Товар.Cтоимость CustomAttributes)
        public virtual double Cтоимость
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Cтоимость Get start)

                // *** End programmer edit section *** (Товар.Cтоимость Get start)
                double result = this.fCтоимость;
                // *** Start programmer edit section *** (Товар.Cтоимость Get end)

                // *** End programmer edit section *** (Товар.Cтоимость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Cтоимость Set start)

                // *** End programmer edit section *** (Товар.Cтоимость Set start)
                this.fCтоимость = value;
                // *** Start programmer edit section *** (Товар.Cтоимость Set end)

                // *** End programmer edit section *** (Товар.Cтоимость Set end)
            }
        }
        
        // *** Start programmer edit section *** (Товар.ПоступлениеТовара CustomAttributes)

        // *** End programmer edit section *** (Товар.ПоступлениеТовара CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void ПоступлениеТовара()
        {
            // *** Start programmer edit section *** (Товар.ПоступлениеТовара method implementation)
            return;
            // *** End programmer edit section *** (Товар.ПоступлениеТовара method implementation)
        }
        
        // *** Start programmer edit section *** (Товар.ПродажаТовара CustomAttributes)

        // *** End programmer edit section *** (Товар.ПродажаТовара CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void ПродажаТовара()
        {
            // *** Start programmer edit section *** (Товар.ПродажаТовара method implementation)
            return;
            // *** End programmer edit section *** (Товар.ПродажаТовара method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварE", typeof(IIS.Интернет_магазин.Товар));
                }
            }
            
            /// <summary>
            /// "ТоварL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварL", typeof(IIS.Интернет_магазин.Товар));
                }
            }
        }
    }
}
